// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NemesiLIB.Context;

#nullable disable

namespace NemesiLIB.Migrations
{
    [DbContext(typeof(GestionaleBertozziContext))]
    [Migration("20260424144314_AggiuntaIsAttivoAdUtente")]
    partial class AggiuntaIsAttivoAdUtente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NemesiLIB.Model.Amministrazione.Collaudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommessaId")
                        .HasColumnType("int");

                    b.Property<string>("Contratto")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<int>("FornitoreId")
                        .HasColumnType("int");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Pagato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ScopoLavoroId")
                        .HasColumnType("int");

                    b.Property<string>("UtenteCreazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommessaId");

                    b.HasIndex("FornitoreId");

                    b.HasIndex("ScopoLavoroId");

                    b.ToTable("Collaudo");
                });

            modelBuilder.Entity("NemesiLIB.Model.Amministrazione.CostoTrasferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Chilometri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("CommessaId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostoChilometri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostoHotel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostoTelepass")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostoTreno")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataA")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataDa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocalitaArrivo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LocalitaPartenza")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UtenteCreazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UtenteModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CommessaId");

                    b.HasIndex("UtenteId");

                    b.ToTable("CostoTrasferta");
                });

            modelBuilder.Entity("NemesiLIB.Model.Amministrazione.Onere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommessaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ImportoOneri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Pratica")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UtenteCreazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommessaId");

                    b.ToTable("Onere");
                });

            modelBuilder.Entity("NemesiLIB.Model.Anagrafiche.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CAP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CodiceFiscale")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Comune")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Indirizzo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ModalitaPagamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartitaIva")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RagioneSociale")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Sdi")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Sigla")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UtenteCreazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModalitaPagamentoId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("NemesiLIB.Model.Anagrafiche.Fornitore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CAP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CodiceFiscale")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Comune")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Indirizzo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ModalitaPagamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nazione")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartitaIva")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RagioneSociale")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Sdi")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Sigla")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UtenteCreazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModalitaPagamentoId");

                    b.ToTable("Fornitore");
                });

            modelBuilder.Entity("NemesiLIB.Model.Anagrafiche.ModalitaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("ModalitaPagamento");
                });

            modelBuilder.Entity("NemesiLIB.Model.Anagrafiche.PersonaleCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mansione")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UtenteCreazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("PersonaleCliente");
                });

            modelBuilder.Entity("NemesiLIB.Model.Anagrafiche.ScopoLavoro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("ScopoLavoro");
                });

            modelBuilder.Entity("NemesiLIB.Model.Anagrafiche.StatusCommessa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Ordine")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StatusCommessa");
                });

            modelBuilder.Entity("NemesiLIB.Model.Anagrafiche.TipologiaCommessa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("TipologiaCommessa");
                });

            modelBuilder.Entity("NemesiLIB.Model.GestioneCommesse.Attivita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completata")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRiferimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Lettera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordine")
                        .HasColumnType("int");

                    b.Property<int>("PercentualeAvanzamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PianoSviluppoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoInfoDaRegistrare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteCreazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PianoSviluppoId");

                    b.ToTable("Attivita");
                });

            modelBuilder.Entity("NemesiLIB.Model.GestioneCommesse.Commessa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("CommessaCodiceInterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("CostoAtteso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataConclusionePrevista")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInizioPrevista")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LuogoCommessa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OrePreviste")
                        .HasColumnType("int");

                    b.Property<string>("PmAmministrativoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PmEdileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProgressivoCommessa")
                        .HasColumnType("int");

                    b.Property<string>("Protocollo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReferentiCliente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StatusCommessaId")
                        .HasColumnType("int");

                    b.Property<int>("TipologiaCommessaId")
                        .HasColumnType("int");

                    b.Property<string>("UtenteCreazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PmAmministrativoId");

                    b.HasIndex("PmEdileId");

                    b.HasIndex("StatusCommessaId");

                    b.HasIndex("TipologiaCommessaId");

                    b.ToTable("Commessa");
                });

            modelBuilder.Entity("NemesiLIB.Model.GestioneCommesse.OreSpeseCommessa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Chilometri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CommessaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("Ore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Spese")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UtenteCreazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UtenteModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommessaId");

                    b.HasIndex("UtenteId");

                    b.ToTable("OreSpeseCommessa");
                });

            modelBuilder.Entity("NemesiLIB.Model.GestioneCommesse.PianoSviluppo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommessaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Ordine")
                        .HasColumnType("int");

                    b.Property<string>("UtenteCreazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommessaId");

                    b.ToTable("PianoSviluppo");
                });

            modelBuilder.Entity("NemesiLIB.Model.GestioneCommesse.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssegnatarioPrimarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssegnatarioSecondarioId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CommessaId")
                        .HasColumnType("int");

                    b.Property<bool>("Completato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DataConsegna")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescrizioneAttivitaSvolta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrizioneTodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Priorita")
                        .HasColumnType("smallint");

                    b.Property<string>("UtenteCreazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssegnatarioPrimarioId");

                    b.HasIndex("AssegnatarioSecondarioId");

                    b.HasIndex("CommessaId");

                    b.ToTable("ToDo");
                });

            modelBuilder.Entity("NemesiLIB.Model.PianiSviluppo.TemplateAttivita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Ordine")
                        .HasColumnType("int");

                    b.Property<int>("PianoSviluppoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoInfoDaRegistrare")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtenteCreazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PianoSviluppoId");

                    b.ToTable("TemplateAttivita");
                });

            modelBuilder.Entity("NemesiLIB.Model.PianiSviluppo.TemplatePianoSviluppo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Ordine")
                        .HasColumnType("int");

                    b.Property<int>("TipologiaCommessaId")
                        .HasColumnType("int");

                    b.Property<string>("UtenteCreazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TipologiaCommessaId");

                    b.ToTable("TemplatePianoSviluppo");
                });

            modelBuilder.Entity("NemesiLIB.Model.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("NemesiLIB.Model.Utente", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CostoKmAuto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoOrario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAttivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEsterno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nominativo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RuoloAziendale")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Societa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NemesiLIB.Model.Utente", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NemesiLIB.Model.Utente", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NemesiLIB.Model.Utente", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NemesiLIB.Model.Utente", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NemesiLIB.Model.Amministrazione.Collaudo", b =>
                {
                    b.HasOne("NemesiLIB.Model.GestioneCommesse.Commessa", "Commessa")
                        .WithMany()
                        .HasForeignKey("CommessaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NemesiLIB.Model.Anagrafiche.Fornitore", "Fornitore")
                        .WithMany()
                        .HasForeignKey("FornitoreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NemesiLIB.Model.Anagrafiche.ScopoLavoro", "ScopoLavoro")
                        .WithMany()
                        .HasForeignKey("ScopoLavoroId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Commessa");

                    b.Navigation("Fornitore");

                    b.Navigation("ScopoLavoro");
                });

            modelBuilder.Entity("NemesiLIB.Model.Amministrazione.CostoTrasferta", b =>
                {
                    b.HasOne("NemesiLIB.Model.Anagrafiche.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NemesiLIB.Model.GestioneCommesse.Commessa", "Commessa")
                        .WithMany()
                        .HasForeignKey("CommessaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NemesiLIB.Model.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Commessa");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("NemesiLIB.Model.Amministrazione.Onere", b =>
                {
                    b.HasOne("NemesiLIB.Model.GestioneCommesse.Commessa", "Commessa")
                        .WithMany()
                        .HasForeignKey("CommessaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Commessa");
                });

            modelBuilder.Entity("NemesiLIB.Model.Anagrafiche.Cliente", b =>
                {
                    b.HasOne("NemesiLIB.Model.Anagrafiche.ModalitaPagamento", "ModalitaPagamento")
                        .WithMany()
                        .HasForeignKey("ModalitaPagamentoId");

                    b.Navigation("ModalitaPagamento");
                });

            modelBuilder.Entity("NemesiLIB.Model.Anagrafiche.Fornitore", b =>
                {
                    b.HasOne("NemesiLIB.Model.Anagrafiche.ModalitaPagamento", "ModalitaPagamento")
                        .WithMany()
                        .HasForeignKey("ModalitaPagamentoId");

                    b.Navigation("ModalitaPagamento");
                });

            modelBuilder.Entity("NemesiLIB.Model.Anagrafiche.PersonaleCliente", b =>
                {
                    b.HasOne("NemesiLIB.Model.Anagrafiche.Cliente", "Cliente")
                        .WithMany("Personale")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("NemesiLIB.Model.GestioneCommesse.Attivita", b =>
                {
                    b.HasOne("NemesiLIB.Model.GestioneCommesse.PianoSviluppo", null)
                        .WithMany("Attivita")
                        .HasForeignKey("PianoSviluppoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NemesiLIB.Model.GestioneCommesse.Commessa", b =>
                {
                    b.HasOne("NemesiLIB.Model.Anagrafiche.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NemesiLIB.Model.Utente", "PmAmministrativo")
                        .WithMany()
                        .HasForeignKey("PmAmministrativoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NemesiLIB.Model.Utente", "PmEdile")
                        .WithMany()
                        .HasForeignKey("PmEdileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NemesiLIB.Model.Anagrafiche.StatusCommessa", "StatusCommessa")
                        .WithMany()
                        .HasForeignKey("StatusCommessaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NemesiLIB.Model.Anagrafiche.TipologiaCommessa", "TipologiaCommessa")
                        .WithMany()
                        .HasForeignKey("TipologiaCommessaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("PmAmministrativo");

                    b.Navigation("PmEdile");

                    b.Navigation("StatusCommessa");

                    b.Navigation("TipologiaCommessa");
                });

            modelBuilder.Entity("NemesiLIB.Model.GestioneCommesse.OreSpeseCommessa", b =>
                {
                    b.HasOne("NemesiLIB.Model.GestioneCommesse.Commessa", null)
                        .WithMany("OreSpese")
                        .HasForeignKey("CommessaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NemesiLIB.Model.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("NemesiLIB.Model.GestioneCommesse.PianoSviluppo", b =>
                {
                    b.HasOne("NemesiLIB.Model.GestioneCommesse.Commessa", null)
                        .WithMany("PianiSviluppo")
                        .HasForeignKey("CommessaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NemesiLIB.Model.GestioneCommesse.ToDo", b =>
                {
                    b.HasOne("NemesiLIB.Model.Utente", "AssegnatarioPrimario")
                        .WithMany()
                        .HasForeignKey("AssegnatarioPrimarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NemesiLIB.Model.Utente", "AssegnatarioSecondario")
                        .WithMany()
                        .HasForeignKey("AssegnatarioSecondarioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NemesiLIB.Model.GestioneCommesse.Commessa", null)
                        .WithMany()
                        .HasForeignKey("CommessaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AssegnatarioPrimario");

                    b.Navigation("AssegnatarioSecondario");
                });

            modelBuilder.Entity("NemesiLIB.Model.PianiSviluppo.TemplateAttivita", b =>
                {
                    b.HasOne("NemesiLIB.Model.PianiSviluppo.TemplatePianoSviluppo", "PianoSviluppo")
                        .WithMany("Attivita")
                        .HasForeignKey("PianoSviluppoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PianoSviluppo");
                });

            modelBuilder.Entity("NemesiLIB.Model.PianiSviluppo.TemplatePianoSviluppo", b =>
                {
                    b.HasOne("NemesiLIB.Model.Anagrafiche.TipologiaCommessa", null)
                        .WithMany()
                        .HasForeignKey("TipologiaCommessaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("NemesiLIB.Model.RefreshToken", b =>
                {
                    b.HasOne("NemesiLIB.Model.Utente", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NemesiLIB.Model.Anagrafiche.Cliente", b =>
                {
                    b.Navigation("Personale");
                });

            modelBuilder.Entity("NemesiLIB.Model.GestioneCommesse.Commessa", b =>
                {
                    b.Navigation("OreSpese");

                    b.Navigation("PianiSviluppo");
                });

            modelBuilder.Entity("NemesiLIB.Model.GestioneCommesse.PianoSviluppo", b =>
                {
                    b.Navigation("Attivita");
                });

            modelBuilder.Entity("NemesiLIB.Model.PianiSviluppo.TemplatePianoSviluppo", b =>
                {
                    b.Navigation("Attivita");
                });
#pragma warning restore 612, 618
        }
    }
}
